services:
  - type: web
    name: av-erp-backend
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: PUPPETEER_SKIP_DOWNLOAD=true npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SUPER_ADMIN_JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false

  - type: web
    name: av-erp-frontend
    env: static
    rootDir: apps/web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
