const crypto = require('crypto');
const DeviceRegistration = require('../models/fingerprint');
const FacultyDeviceMapping = require('../models/FacultyDeviceMapping');
const FacultyAttendance = require('../models/FacultyAttendance');
const { addPunch, getQueueStats } = require('../services/punchQueue');

// ─── DEVICE MANAGEMENT ────────────────────────────────────────────────────────

/**
 * POST /api/v1/fingerprint/device
 * Admin registers a new MORX device. Token is auto-generated.
 */
exports.registerDevice = async (req, res) => {
  try {
    const { deviceName, serialNumber, location } = req.body;
    const schoolId = req.schoolId; // set by auth middleware

    const device = await DeviceRegistration.create({
      schoolId,
      deviceName,
      serialNumber,
      location,
      // token auto-generated by model pre-validate hook
    });

    res.status(201).json({
      success: true,
      message: 'Device registered successfully',
      data: {
        _id: device._id,
        deviceName: device.deviceName,
        location: device.location,
        token: device.token, // show once — admin configures this in device
        pushUrl: `${process.env.SERVER_URL || 'http://localhost:4000'}/api/v1/device/punch`,
        isActive: device.isActive,
        createdAt: device.createdAt,
      },
    });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(409).json({ success: false, message: 'A device with this name already exists for your school' });
    }
    res.status(400).json({ success: false, message: err.message });
  }
};

/**
 * GET /api/v1/fingerprint/device
 * List all devices for admin's school.
 */
exports.getDevices = async (req, res) => {
  try {
    const devices = await DeviceRegistration.find({ schoolId: req.schoolId })
      .sort({ createdAt: -1 })
      .select('-__v');

    res.json({ success: true, data: devices });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

/**
 * PATCH /api/v1/fingerprint/device/:id/toggle
 * Enable / disable a device.
 */
exports.toggleDevice = async (req, res) => {
  try {
    const device = await DeviceRegistration.findOne({ _id: req.params.id, schoolId: req.schoolId });
    if (!device) return res.status(404).json({ success: false, message: 'Device not found' });

    device.isActive = !device.isActive;
    await device.save();

    res.json({ success: true, message: `Device ${device.isActive ? 'activated' : 'deactivated'}`, data: device });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

/**
 * DELETE /api/v1/fingerprint/device/:id
 */
exports.deleteDevice = async (req, res) => {
  try {
    const device = await DeviceRegistration.findOneAndDelete({ _id: req.params.id, schoolId: req.schoolId });
    if (!device) return res.status(404).json({ success: false, message: 'Device not found' });

    // Also remove all faculty mappings for this device
    await FacultyDeviceMapping.deleteMany({ deviceId: device._id, schoolId: req.schoolId });

    res.json({ success: true, message: 'Device and all its mappings deleted' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── FACULTY MAPPING ──────────────────────────────────────────────────────────

/**
 * POST /api/v1/fingerprint/mapping
 * Map a faculty member to a device user ID.
 */
exports.mapFaculty = async (req, res) => {
  try {
    const { deviceId, facultyId, deviceUserId } = req.body;
    const schoolId = req.schoolId;

    // Verify device belongs to this school
    const device = await DeviceRegistration.findOne({ _id: deviceId, schoolId });
    if (!device) return res.status(404).json({ success: false, message: 'Device not found' });

    const mapping = await FacultyDeviceMapping.create({
      schoolId,
      deviceId,
      facultyId,
      deviceUserId: String(deviceUserId),
      enrolledBy: req.userid,
    });

    await mapping.populate('facultyId', 'firstName lastName employeeId');

    res.status(201).json({ success: true, message: 'Faculty mapped successfully', data: mapping });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(409).json({
        success: false,
        message: 'This faculty or device user ID is already mapped. Remove the existing mapping first.',
      });
    }
    res.status(400).json({ success: false, message: err.message });
  }
};

/**
 * GET /api/v1/fingerprint/mapping
 */
exports.getMappings = async (req, res) => {
  try {
    const mappings = await FacultyDeviceMapping.find({ schoolId: req.schoolId, isActive: true })
      .populate('facultyId', 'firstName lastName employeeId designation')
      .populate('deviceId', 'deviceName location')
      .sort({ createdAt: -1 });

    res.json({ success: true, data: mappings });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

/**
 * DELETE /api/v1/fingerprint/mapping/:id
 */
exports.deleteMapping = async (req, res) => {
  try {
    const mapping = await FacultyDeviceMapping.findOneAndDelete({ _id: req.params.id, schoolId: req.schoolId });
    if (!mapping) return res.status(404).json({ success: false, message: 'Mapping not found' });

    res.json({ success: true, message: 'Mapping removed' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── DEVICE PUNCH ENDPOINT ────────────────────────────────────────────────────

/**
 * POST /api/v1/device/punch
 * Called by the physical MORX device when a fingerprint is scanned.
 * NO JWT auth — uses X-Device-Token header instead.
 *
 * Expected body from MORX device:
 * { uid: "001", time: "2025-03-30T09:05:00Z" }
 * OR the device may send: { id: "001", datetime: "..." } — handle both.
 */
exports.receivePunch = async (req, res) => {
  const token = req.headers['x-device-token'] || req.query.token;

  if (!token) {
    return res.status(401).json({ success: false, message: 'Device token required' });
  }

  try {
    // Validate token → get device + school
    const device = await DeviceRegistration.findOne({ token, isActive: true }).lean();
    if (!device) {
      return res.status(403).json({ success: false, message: 'Invalid or inactive device token' });
    }

    // Parse device payload — MORX sends different field names on different firmware
    const deviceUserId = String(
      req.body.uid || req.body.id || req.body.user_id || req.body.userId || ''
    );
    const punchTimeRaw = req.body.time || req.body.datetime || req.body.timestamp || new Date().toISOString();
    const punchTime = new Date(punchTimeRaw);

    if (!deviceUserId) {
      return res.status(400).json({ success: false, message: 'User ID missing in punch data' });
    }

    if (isNaN(punchTime.getTime())) {
      return res.status(400).json({ success: false, message: 'Invalid punch timestamp' });
    }

    // Enqueue for async processing — respond immediately so device doesn't timeout
    const jobId = await addPunch({
      schoolId: device.schoolId.toString(),
      deviceId: device._id.toString(),
      deviceUserId,
      punchTime: punchTime.toISOString(),
      rawPayload: JSON.stringify(req.body),
    });

    // Fast 200 response — device needs this within 500ms
    res.json({ success: true, queued: true, jobId });

  } catch (err) {
    console.error('[receivePunch] Error:', err.message);
    res.status(500).json({ success: false, message: 'Server error' });
  }
};

// ─── ATTENDANCE QUERY ─────────────────────────────────────────────────────────

/**
 * GET /api/v1/fingerprint/attendance?date=2025-03-30
 * Get all faculty attendance for a specific date.
 */
exports.getAttendance = async (req, res) => {
  try {
    const { date, month, year, facultyId } = req.query;
    const schoolId = req.schoolId;

    let query = { schoolId };

    if (date) {
      const d = new Date(date);
      const startOfDay = new Date(d.getFullYear(), d.getMonth(), d.getDate());
      const endOfDay = new Date(startOfDay.getTime() + 86400000);
      query.date = { $gte: startOfDay, $lt: endOfDay };
    } else if (month && year) {
      const startOfMonth = new Date(year, month - 1, 1);
      const endOfMonth = new Date(year, month, 1);
      query.date = { $gte: startOfMonth, $lt: endOfMonth };
    } else {
      // Default: today
      const today = new Date();
      const startOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate());
      const endOfDay = new Date(startOfDay.getTime() + 86400000);
      query.date = { $gte: startOfDay, $lt: endOfDay };
    }

    if (facultyId) query.facultyId = facultyId;

    const records = await FacultyAttendance.find(query)
      .populate('facultyId', 'firstName lastName employeeId designation department documents')
      .sort({ date: -1, 'facultyId.firstName': 1 });

    // Summary
    const summary = {
      total: records.length,
      present: records.filter(r => r.status === 'present').length,
      late: records.filter(r => r.status === 'late').length,
      absent: records.filter(r => r.status === 'absent').length,
      halfDay: records.filter(r => r.status === 'half_day').length,
      onLeave: records.filter(r => r.status === 'on_leave').length,
    };

    res.json({ success: true, summary, data: records });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

/**
 * POST /api/v1/fingerprint/attendance/manual
 * Admin manually corrects or adds attendance.
 */
exports.manualCorrection = async (req, res) => {
  try {
    const { facultyId, date, punchIn, punchOut, status, note } = req.body;
    const schoolId = req.schoolId;

    const d = new Date(date);
    const dateOnly = new Date(d.getFullYear(), d.getMonth(), d.getDate());

    const update = {
      source: 'manual',
      manuallyUpdatedBy: req.userid,
      manualNote: note,
    };
    if (punchIn) update.punchIn = new Date(punchIn);
    if (punchOut) update.punchOut = new Date(punchOut);
    if (status) update.status = status;

    const record = await FacultyAttendance.findOneAndUpdate(
      { schoolId, facultyId, date: dateOnly },
      { $set: update },
      { new: true, upsert: true, runValidators: true }
    ).populate('facultyId', 'firstName lastName');

    res.json({ success: true, message: 'Attendance updated', data: record });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

/**
 * GET /api/v1/fingerprint/report/monthly?month=3&year=2025&facultyId=xxx
 */
exports.getMonthlyReport = async (req, res) => {
  try {
    const { month, year, facultyId } = req.query;
    const schoolId = req.schoolId;

    const startOfMonth = new Date(year, month - 1, 1);
    const endOfMonth = new Date(year, month, 1);

    const query = { schoolId, date: { $gte: startOfMonth, $lt: endOfMonth } };
    if (facultyId) query.facultyId = facultyId;

    const records = await FacultyAttendance.find(query)
      .populate('facultyId', 'firstName lastName employeeId designation')
      .sort({ facultyId: 1, date: 1 });

    // Group by faculty
    const grouped = {};
    records.forEach(r => {
      const id = r.facultyId?._id?.toString();
      if (!grouped[id]) {
        grouped[id] = {
          faculty: r.facultyId,
          present: 0, late: 0, absent: 0, halfDay: 0, onLeave: 0,
          totalHours: 0,
          records: [],
        };
      }
      grouped[id].records.push(r);
      grouped[id].totalHours += r.totalHours || 0;
      if (r.status === 'present') grouped[id].present++;
      else if (r.status === 'late') grouped[id].late++;
      else if (r.status === 'absent') grouped[id].absent++;
      else if (r.status === 'half_day') grouped[id].halfDay++;
      else if (r.status === 'on_leave') grouped[id].onLeave++;
    });

    res.json({ success: true, data: Object.values(grouped) });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

/**
 * GET /api/v1/fingerprint/queue/stats
 * Admin can see queue health.
 */
exports.getQueueHealth = async (req, res) => {
  try {
    const stats = await getQueueStats();
    res.json({ success: true, data: stats });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── CSV UPLOAD (for devices without HTTP push) ───────────────────────────────

/**
 * POST /api/v1/fingerprint/attendance/upload-csv
 * Admin downloads attendance log from MORX software → uploads CSV here.
 *
 * Supported MORX CSV column formats (auto-detected):
 *   User ID / No. / EmpCode / DeviceUserID  → deviceUserId
 *   Date Time / DateTime / Time / Punch Time → punchTime
 *   Device / DeviceName / DeviceID          → optional, for multi-device files
 *
 * Body (multipart/form-data):
 *   file     → CSV file
 *   deviceId → which registered device this CSV came from (ObjectId)
 */
exports.uploadAttendanceCSV = async (req, res) => {
  try {
    const { deviceId } = req.body;
    if (!req.file) return res.status(400).json({ success: false, message: 'CSV file required' });
    if (!deviceId) return res.status(400).json({ success: false, message: 'deviceId required (select which device this CSV is from)' });

    // Verify device belongs to this school
    const device = await DeviceRegistration.findOne({ _id: deviceId, schoolId: req.schoolId });
    if (!device) return res.status(404).json({ success: false, message: 'Device not found' });

    // ── Parse CSV from buffer ────────────────────────────────────────────────
    const csvText = req.file.buffer.toString('utf-8');
    const lines = csvText.split(/\r?\n/).filter(l => l.trim());
    if (lines.length < 2) return res.status(400).json({ success: false, message: 'CSV is empty or has no data rows' });

    // Parse header row — normalize to lowercase, trim spaces
    const headers = lines[0].split(',').map(h => h.trim().toLowerCase().replace(/[^a-z0-9]/g, ''));

    // Detect column indices (flexible — handles different MORX software versions)
    const findCol = (...names) => {
      for (const name of names) {
        const idx = headers.indexOf(name.toLowerCase().replace(/[^a-z0-9]/g, ''));
        if (idx !== -1) return idx;
      }
      return -1;
    };

    const userIdCol   = findCol('userid', 'no', 'empcode', 'deviceuserid', 'id', 'enrollno');
    const timeCol     = findCol('datetime', 'date time', 'punchtime', 'time', 'checktime', 'timestamp');

    if (userIdCol === -1 || timeCol === -1) {
      return res.status(400).json({
        success: false,
        message: `Could not detect required columns. Found headers: [${headers.join(', ')}]. Need: User ID (or No/EmpCode) AND DateTime (or Time/PunchTime)`,
      });
    }

    // ── Process each data row ────────────────────────────────────────────────
    const results = { processed: 0, skipped: 0, errors: [] };

    for (let i = 1; i < lines.length; i++) {
      const cols = lines[i].split(',').map(c => c.trim().replace(/^"|"$/g, '')); // strip quotes
      const deviceUserId = cols[userIdCol]?.trim();
      const rawTime      = cols[timeCol]?.trim();

      if (!deviceUserId || !rawTime) {
        results.errors.push(`Row ${i + 1}: Missing user ID or time — skipped`);
        results.skipped++;
        continue;
      }

      const punchTime = new Date(rawTime);
      if (isNaN(punchTime.getTime())) {
        results.errors.push(`Row ${i + 1}: Invalid date "${rawTime}" — skipped`);
        results.skipped++;
        continue;
      }

      // Find faculty mapping
      const mapping = await FacultyDeviceMapping.findOne({
        schoolId: req.schoolId,
        deviceId: device._id,
        deviceUserId: String(deviceUserId),
        isActive: true,
      });

      if (!mapping) {
        results.errors.push(`Row ${i + 1}: No mapping for deviceUserId="${deviceUserId}" — skipped`);
        results.skipped++;
        continue;
      }

      // Upsert attendance record (same logic as worker)
      const dateOnly = new Date(punchTime.getFullYear(), punchTime.getMonth(), punchTime.getDate());

      const existing = await FacultyAttendance.findOne({
        schoolId: req.schoolId,
        facultyId: mapping.facultyId,
        date: dateOnly,
      });

      const rawPunchEntry = {
        time: punchTime,
        deviceUserId: String(deviceUserId),
        deviceId: device._id,
        queueJobId: `csv-upload-row-${i}`,
      };

      if (!existing) {
        await FacultyAttendance.create({
          schoolId: req.schoolId,
          facultyId: mapping.facultyId,
          date: dateOnly,
          punchIn: punchTime,
          source: 'device',
          rawPunches: [rawPunchEntry],
        });
      } else {
        existing.rawPunches.push(rawPunchEntry);
        if (!existing.punchOut || punchTime > existing.punchOut) existing.punchOut = punchTime;
        if (existing.punchIn && punchTime < existing.punchIn) existing.punchIn = punchTime;
        await existing.save(); // triggers pre-save: recalculates totalHours + status
      }

      results.processed++;
    }

    // Update device stats
    await DeviceRegistration.findByIdAndUpdate(deviceId, {
      lastPingAt: new Date(),
      $inc: { totalPunches: results.processed },
    });

    res.json({
      success: true,
      message: `CSV processed: ${results.processed} punches recorded, ${results.skipped} skipped`,
      data: results,
    });
  } catch (err) {
    console.error('[uploadAttendanceCSV] Error:', err.message);
    res.status(500).json({ success: false, message: err.message });
  }
};
